FROM mcr.microsoft.com/dotnet/sdk:10.0 AS dev

RUN apt-get update \
    && apt-get install -y tini curl nodejs npm \
    && npm install -g nodemon \
    && apt-get clean

ARG FOLDER=/app

COPY --chown=1000:1000 . /app

WORKDIR $FOLDER

USER 1000:1000

EXPOSE 5103

ENV ASPNETCORE_URLS=http://0.0.0.0:5103

ENV ASPNETCORE_ENVIRONMENT=Development

ENV ASPNETCORE_HTTPS_PORT=""

ENV DOTNET_USE_POLLING_FILE_WATCHER=1

ENTRYPOINT ["/usr/bin/tini", "--"]

CMD ["nodemon"]